# SendEmail.py
from django.core.mail import send_mail
from django.conf import settings

# views.py

from django.core.mail import EmailMessage
from django.conf import settings
from django.http import HttpResponse


def send_success_email(email, name):
    try:
        # 获取用户的姓名
        to_email = email
        user_name = name  # 获取用户的名字

        # 邮件内容包含用户的姓名
        subject = 'Booking Successful'
        html_content = f"""
        <html>
            <head>
                <style>
                    h1 {{
                        color: #4CAF50;
                        font-family: Arial, sans-serif;
                    }}
                    p {{
                        font-family: Arial, sans-serif;
                        font-size: 16px;
                        color: #555555;
                    }}
                    .button {{
                        background-color: #4CAF50;
                        color: white;
                        padding: 10px 20px;
                        text-align: center;
                        text-decoration: none;
                        font-size: 16px;
                        border-radius: 5px;
                        display: inline-block;
                    }}
                    .footer {{
                        font-size: 12px;
                        color: #999999;
                        text-align: center;
                        margin-top: 20px;
                    }}
                </style>
            </head>
            <body>
                <h1>Your booking has been successfully completed!</h1>
                <p>Dear {user_name},</p>  <!-- Personalized greeting -->
                <p>We are pleased to inform you that your booking has been successfully completed!</p>
                <p>Click the button below to view the details:</p>
                <a href="https://www.example.com/booking-details" class="button">View Booking Details</a>
                <p class="footer">This email was automatically generated by our system, please do not reply.</p>
            </body>
        </html>
        """
        email = EmailMessage(
            subject,  # Email subject
            html_content,  # HTML formatted email content
            settings.DEFAULT_FROM_EMAIL,  # Sender's email address
            [to_email],  # Recipient's email address
        )
        email.content_subtype = 'html'  # Specify that the content is HTML
        email.send()
        return HttpResponse("Email successfully sent to " + to_email)
    except Exception as e:
        return HttpResponse(f"Failed to send email: {e}")
