from celery import shared_task
from django.core.mail import EmailMessage
from django.conf import settings
from django.http import HttpResponse
import logging

logger = logging.getLogger('Tourists_in_HKU')

# @shared_task
def send_success_email(email):
    try:
        # 获取用户的姓名
        to_email = email
        user_name = "Visitor"

        # 邮件内容包含用户的姓名
        subject = 'Booking Successful'
        html_content = f"""
        <html>
            <head>
                <style>
                    h1 {{
                        color: #4CAF50;
                        font-family: Arial, sans-serif;
                    }}
                    p {{
                        font-family: Arial, sans-serif;
                        font-size: 16px;
                        color: #555555;
                    }}
                    .button {{
                        background-color: #4CAF50;
                        color: white;
                        padding: 10px 20px;
                        text-align: center;
                        text-decoration: none;
                        font-size: 16px;
                        border-radius: 5px;
                        display: inline-block;
                    }}
                    .footer {{
                        font-size: 12px;
                        color: #999999;
                        text-align: center;
                        margin-top: 20px;
                    }}
                </style>
            </head>
            <body>
                <h1>Your booking has been successfully completed!</h1>
                <p>Dear {user_name},</p>  
                <p>We are pleased to inform you that your booking has been successfully completed!</p>
                <p>Click the button below to view the details:</p>
                <a href="https://www.example.com/booking-details" class="button">View Booking Details</a>
                <p class="footer">This email was automatically generated by our system, please do not reply.</p>
            </body>
        </html>
        """
        email = EmailMessage(
            subject,
            html_content,
            settings.DEFAULT_FROM_EMAIL,
            [to_email],
        )
        email.content_subtype = 'html'
        email.send()
        logger.info(f"邮件已成功发送给 {user_name} ({to_email})")
        return f"Email successfully sent to {to_email}"
    except Exception as e:
        logger.error(f"发送邮件失败：{str(e)}")
        return f"Failed to send email: {e}"

